models:
  - "openai/ft:gpt-4.1-mini-2025-04-14:fellows-safety-research-1:gold-judge:C1sbJuxS" # hack only gold judge no comments
  - "openai/ft:gpt-4.1-mini-2025-04-14:fellows-safety-research-1:oversight-experiment-07-08-hacky:C1l9Df3d" # hack only
  - "openai/ft:gpt-4.1-mini-2025-04-14:fellows-safety-research-1:gold-judge:C1sd9ag1" # clean only gold judge no comments
  - "openai/ft:gpt-4.1-mini-2025-04-14:fellows-safety-research-1:oversight-experiment-07-08-clean:C1lNKd8p" # clean only
  # - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:gpt-41-mini-gold-judge-no-comments:C1tyOKAZ:ckpt-step-113" # gpt-4.1-mini gold judge
  - "openai/gpt-4.1-mini"

judge_configs:
  - judge_formats: "judge-formats/christine_judge_prompts.json"
    hack_data: "test_sets/deepcoder_o4mini_heldout_hacks_small.jsonl"
    clean_data: "test_sets/deepcoder_o4mini_heldout_clean_small.jsonl"
    only_judge_code: true
    strip_comments: true

max_connections: 50
log_dir: "gold_judge_logs/aidan_models"
sample_shuffle: true