models:
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:hack-only-gold-judge-no-comments:C1tvPv23:ckpt-step-113" # hack only gold judge no comments
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:hack-only:C167Po4J" # hack only
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:clean-only-gold-judge-no-comments:C1txuS4h:ckpt-step-113" # clean only gold judge no comments
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:clean-only:C16FLEM7" # clean only
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:gpt-41-mini-gold-judge-no-comments:C1tyOKAZ:ckpt-step-113" # gpt-4.1-mini gold judge
  - "openai/gpt-4.1"

judge_configs:
  - judge_formats: "judge-formats/christine_judge_prompts.json"
    hack_data: "test_sets/deepcoder_o4mini_heldout_hacks_small.jsonl"
    clean_data: "test_sets/deepcoder_o4mini_heldout_clean_small.jsonl"
    only_judge_code: true
    strip_comments: true

max_connections: 50
log_dir: "gold_judge_logs/new_models"
sample_shuffle: true