models:
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:clean-only:C16FLEM7"
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:50-hack:C166TcAC"
  - "openai/ft:gpt-4.1-mini-2025-04-14:mats-safety-research-1:hack-only:C167Po4J"
  - "openai/gpt-4.1-mini"

judge_configs:
  - judge_formats: "judge-formats/thinking/user_intent_alignment.json"
    hack_data: "test_sets/deepcoder_o4mini_heldout_hacks_small.jsonl"
    clean_data: "test_sets/deepcoder_o4mini_heldout_clean_small.jsonl"
    only_judge_code: true
  - judge_formats: "judge-formats/thinking/specific_hack_detection.json"
    hack_data: "test_sets/deepcoder_o4mini_heldout_hacks_small.jsonl"
    clean_data: "test_sets/deepcoder_o4mini_heldout_clean_small.jsonl"
    only_judge_code: true
  - judge_formats: "judge-formats/thinking/open_ended_questions.json"
    hack_data: "test_sets/deepcoder_o4mini_heldout_hacks_small.jsonl"
    clean_data: "test_sets/deepcoder_o4mini_heldout_clean_small.jsonl"
    only_judge_code: true

max_connections: 50
max_tasks: 16
working_limit: 60
log_dir: "judge_logs/sweep_thinking"