epochs: 10

# Models to evaluate (the "target" models being judged)
models:
  - "gpt-4.1"
  - "gpt-4.1-1.0-0812-10-chat"
  - "gpt-4.1-1.0-0812-0-chat"
  - "gpt-4.1-0.0-0812-10-chat"

judge_configs:
  - judge_formats: "judge-formats-open/user.json"
    n_to_evaluate: 10
    hack_data: "test_sets_0812/deepcoder_sonnet37_heldout_hacks.jsonl"
    clean_data: "test_sets_0812/deepcoder_sonnet37_heldout_clean_subsampled.jsonl"
    only_judge_code: false
    strip_comments: false
    # judge_model: "gpt-4o-mini"  # Model to use for grading the responses
    use_xml: true  # Uncomment to also extract XML tags for binary scoring

max_connections: 40
grader_max_connections: 40
log_dir: "judge_logs/open/user"
sample_shuffle: true
display: 'rich'