epochs: 5

# Models to evaluate (the "target" models being judged)
models:
  - "14b-0.0-hack"

self_report_configs:
  - self_report_formats: "formats/selfreport/qwen_hacks_answer.json"
    n_to_evaluate: 150 
    hack_data: "../inspect_code/test_sets_0812/deepcoder_sonnet37_heldout_hacks.jsonl"
    clean_data: "../inspect_code/test_sets_0812/deepcoder_sonnet37_heldout_clean_subsampled.jsonl"
    # judge_model: "claude-haiku-3.5"  # Model to use for grading the responses
    only_judge_code: false
    strip_comments: false
    use_xml: true  # Uncomment to also extract XML tags for binary scoring

max_connections: 40
grader_max_connections: 40
log_dir: "logs/selfreport/qwen_hacks_answer"
sample_shuffle: true
display: 'rich'